// ─────────────────────────────────────────────────────────────────────────────
// SITE CONFIGURATION — edit this file to update practice info across the site
// ─────────────────────────────────────────────────────────────────────────────

export const SITE = {
  name: "ParikhHealth",
  tagline: "Exceptional Primary Care & Sports Medicine",
  description:
    "ParikhHealth is a premier primary care and sports medicine practice in Sunnyvale, CA — delivering compassionate, evidence-based medicine for every stage of life.",
  url: "https://www.parikhhealth.com",
  phone: {
    appointments: "408-266-3100",
    general: "408-266-3100",
    fax: "408-608-1961",
  },
  email: "support@parikhhealth.com",
  address: {
    street: "1299 Oakmead Parkway",
    city: "Sunnyvale",
    state: "CA",
    zip: "94085",
    full: "1299 Oakmead Parkway, Sunnyvale, CA 94085",
    mapsUrl:
      "https://maps.google.com/?q=1299+Oakmead+Parkway+Sunnyvale+CA+94085",
  },
  hours: [
    { day: "Monday – Friday", hours: "9:00 AM – 4:00 PM" },
    { day: "Saturday – Sunday", hours: "Closed" },
  ],
  // Appointment booking — set provider to "zocdoc" | "calendly" | "custom"
  booking: {
    provider: "zocdoc" as "zocdoc" | "calendly" | "custom",
    zocdocUrl: "https://www.zocdoc.com/booking-link/practice/parikhhealth-13809",
    calendlyUrl: "", // fill in if switching to Calendly
  },
  social: {
    google: "https://g.page/parikhhealth",
    instagram: "",
    facebook: "",
    linkedin: "",
  },
  rating: { score: 4.78, count: 201, source: "Google" },
};

export const TEAM = [
  {
    id: "neesheet-parikh",
    name: "Neesheet Parikh",
    credentials: "DO",
    title: "Physician — Family Medicine & Sports Medicine",
    bio: "Dr. Parikh is a board-certified family medicine and sports medicine physician with a passion for keeping patients active and healthy at every stage of life. He completed his osteopathic medical training and brings a whole-body, integrative approach to primary care.",
    image: "/team/dr-parikh.jpg",
    specialties: ["Family Medicine", "Sports Medicine", "Osteopathic Manipulative Therapy", "Concierge Medicine"],
    acceptingNewPatients: true,
    bookingUrl: "https://www.zocdoc.com/booking-link/doctor/neesheet-parikh-do-29659",
  },
  {
    id: "kinnari-shah",
    name: "Kinnari Shah",
    credentials: "PA-C",
    title: "Physician Assistant",
    bio: "Kinnari Shah is a certified physician assistant who delivers thorough, patient-centered primary care. She partners closely with patients to manage chronic conditions, preventive health, and acute illnesses with warmth and precision.",
    image: "/team/kinnari-shah.jpg",
    specialties: ["Primary Care", "Preventive Medicine", "Chronic Disease Management"],
    acceptingNewPatients: true,
    bookingUrl: "https://www.zocdoc.com/booking-link/doctor/kinnari-shah-pa-c-451056",
  },
  {
    id: "miral-patel",
    name: "Miral Patel",
    credentials: "PT",
    title: "Physical Therapist",
    bio: "Miral Patel is a licensed physical therapist specializing in sports rehabilitation and musculoskeletal recovery. Utilizing cutting-edge tools including Fit3D body scanning, she designs individualized programs that get patients back to the activities they love.",
    image: "/team/miral-patel.jpg",
    specialties: ["Sports Rehabilitation", "Musculoskeletal Therapy", "Fit3D Body Scanning", "Post-Surgical Recovery"],
    acceptingNewPatients: true,
  },
  {
    id: "sonia-sharma",
    name: "Sonia Sharma",
    credentials: "PT",
    title: "Physical Therapist",
    bio: "Sonia Sharma is a licensed physical therapist dedicated to helping patients recover from injury and return to the activities they love. She brings expertise in orthopedic and sports rehabilitation to every treatment plan.",
    image: "/team/sonia-sharma.jpg",
    specialties: ["Orthopedic Rehabilitation", "Sports Therapy", "Manual Therapy"],
    acceptingNewPatients: true,
  },
  {
    id: "harshit-bhatwala",
    name: "Harshit Bhatwala",
    credentials: "PT",
    title: "Physical Therapist",
    bio: "Harshit Bhatwala is a licensed physical therapist focused on evidence-based care and personalized rehabilitation. He works closely with patients to restore strength, mobility, and confidence after injury or surgery.",
    image: "/team/harshit-bhatwala.jpg",
    specialties: ["Sports Rehabilitation", "Post-Surgical Recovery", "Therapeutic Exercise"],
    acceptingNewPatients: true,
  },
  {
    id: "vaishali-parab",
    name: "Vaishali Parab",
    credentials: "PTA",
    title: "Physical Therapist Assistant",
    bio: "Vaishali Parab is a physical therapist assistant who works alongside our PT team to deliver hands-on rehabilitation and therapeutic exercise programs tailored to each patient's recovery goals.",
    image: "/team/vaishali-parab.jpg",
    specialties: ["Therapeutic Exercise", "Rehabilitation Support", "Patient Education"],
    acceptingNewPatients: true,
  },
];

export const SUPPORT_STAFF = [
  { name: "Gabriela Montiel", title: "Office Manager" },
  { name: "Ami Desai", title: "Medical Assistant & Phlebotomist" },
  { name: "Duncan Chisholm", title: "Medical Assistant & Phlebotomist" },
  { name: "Aarushi Kumar", title: "Front Desk" },
  { name: "Vivi Le", title: "PT Aide" },
  { name: "Jazmyn Henry", title: "PT Aide" },
  { name: "Earl Dela Rosa", title: "PT Aide" },
  { name: "Neha Shah", title: "PT Aide" },
  { name: "Saurabh Bhatt", title: "Billing Specialist" },
];

export const SERVICES = [
  {
    id: "primary-care",
    name: "Primary Care",
    shortDesc: "Comprehensive, relationship-based care for every stage of life.",
    description:
      "Our primary care team serves as your long-term health partner — managing preventive screenings, chronic conditions, acute illnesses, and coordinating specialist referrals when needed. We prioritize continuity of care so we can truly know you, not just your chart.",
    icon: "stethoscope",
    highlights: [
      "Annual wellness exams",
      "Chronic disease management (diabetes, hypertension, cholesterol)",
      "Preventive screenings & immunizations",
      "Sick visits & acute care",
      "Laboratory & diagnostic services",
    ],
    image: "/services/primary-care.jpg",
  },
  {
    id: "sports-medicine",
    name: "Sports Medicine",
    shortDesc: "Expert care for athletes and active individuals.",
    description:
      "From weekend warriors to competitive athletes, our sports medicine program focuses on injury prevention, rapid recovery, and performance optimization. Dr. Parikh applies both osteopathic and evidence-based sports medicine principles to get you back in the game.",
    icon: "activity",
    highlights: [
      "Sports injury evaluation & treatment",
      "Musculoskeletal injections (cortisone, PRP)",
      "Pre-participation physicals",
      "Return-to-sport clearance",
      "Overuse injury management",
    ],
    image: "/services/sports-medicine.jpg",
  },
  {
    id: "physical-therapy",
    name: "Physical Therapy",
    shortDesc: "Personalized rehabilitation with state-of-the-art technology.",
    description:
      "Our in-house physical therapy program, led by Miral Patel PT, combines manual therapy, therapeutic exercise, and the Fit3D body scanner to precisely track your progress. Having PT in-house with your medical team means seamlessly coordinated care.",
    icon: "dumbbell",
    highlights: [
      "Orthopedic & sports rehabilitation",
      "Fit3D body composition scanning",
      "Post-surgical recovery",
      "Balance & gait training",
      "Manual therapy & soft tissue techniques",
    ],
    image: "/services/physical-therapy.jpg",
  },
  {
    id: "cosmetics",
    name: "Cosmetic Services",
    shortDesc: "Medical-grade aesthetics with a physician's expertise.",
    description:
      "Looking your best supports feeling your best. Our cosmetic services are performed under physician oversight, ensuring safety and natural-looking results — no med-spa guesswork.",
    icon: "sparkles",
    highlights: [
      "Botox & neurotoxin treatments",
      "Dermal fillers",
      "Skin rejuvenation",
      "Medical-grade skincare",
    ],
    image: "/services/cosmetics.jpg",
  },
  {
    id: "womens-health",
    name: "Women's Health",
    shortDesc: "Compassionate, comprehensive care for women at every stage of life.",
    description:
      "Our women's health services provide a comfortable, thorough approach to preventive care and gynecologic health. We believe every woman deserves a provider who listens carefully and takes her concerns seriously — whether she's coming in for a routine exam or navigating a new health question.",
    icon: "heart",
    highlights: [
      "Annual well-woman exams",
      "Pap smears & cervical cancer screening",
      "Clinical breast exams",
      "Contraception counseling & management",
      "Menstrual health & hormone discussions",
      "STI screening & sexual health",
      "Menopause & perimenopause support",
      "Referrals to OB/GYN specialists when needed",
    ],
    conditionsTreated: [
      {
        category: "Preventive & Wellness",
        items: [
          "Annual well-woman exams",
          "Pap smears / cervical cancer screening",
          "Breast cancer screening (mammogram orders, clinical breast exams)",
          "Osteoporosis screening (DEXA ordering)",
          "STI screening",
          "Immunizations (HPV vaccine, etc.)",
        ],
      },
      {
        category: "Reproductive & Gynecologic",
        items: [
          "Contraception management (pills, patch, ring, IUD counseling, Nexplanon)",
          "Dysmenorrhea (painful periods)",
          "Menorrhagia / abnormal uterine bleeding",
          "PCOS (Polycystic Ovary Syndrome)",
          "PMS / PMDD",
          "Vaginitis (bacterial vaginosis, yeast, trichomoniasis)",
          "UTIs / recurrent UTIs",
          "Pelvic inflammatory disease (initial management)",
          "Endometriosis (diagnosis, co-management)",
          "Uterine fibroids (co-management)",
          "Ovarian cysts (monitoring, referral coordination)",
        ],
      },
      {
        category: "Menopause & Hormones",
        items: [
          "Perimenopause / menopause management",
          "Hormone replacement therapy (HRT) — initiation & monitoring",
          "Genitourinary syndrome of menopause (GSM)",
          "Sexual dysfunction / low libido",
          "Premature ovarian insufficiency",
        ],
      },
      {
        category: "Pregnancy-Adjacent",
        items: [
          "Preconception counseling",
          "Prenatal labs and first trimester care (if not OB)",
          "Postpartum depression / anxiety",
          "Lactation support (basic)",
        ],
      },
      {
        category: "Mental Health (Women-Specific)",
        items: [
          "Postpartum depression & anxiety",
          "Perinatal mood disorders",
          "Depression/anxiety with hormonal correlations",
          "Eating disorders (initial evaluation)",
        ],
      },
      {
        category: "Cardiometabolic (Women-Specific Presentations)",
        items: [
          "Hypertension in women / pregnancy-related hypertension history",
          "Metabolic syndrome / insulin resistance (often tied to PCOS)",
          "Thyroid disorders (hypothyroidism, Hashimoto's — very common in women)",
          "Anemia (iron deficiency, B12)",
        ],
      },
      {
        category: "Musculoskeletal",
        items: [
          "Osteoporosis / osteopenia management",
          "Hypermobility (more prevalent in women)",
          "Fibromyalgia",
          "Frozen shoulder",
        ],
      },
      {
        category: "Pelvic Floor (Co-management with PT)",
        items: [
          "Urinary incontinence (stress, urge, mixed)",
          "Pelvic organ prolapse (evaluation, referral)",
          "Interstitial cystitis / bladder pain syndrome",
        ],
      },
    ],
    image: "/services/womens-health.jpg",
  },
  {
    id: "concierge-medicine",
    name: "Concierge Medicine",
    shortDesc: "Unhurried care, direct access, and a true medical partnership.",
    description:
      "For patients who want more — more time with their doctor, same-day access, and a physician who knows every detail of their health — our concierge program offers a premium, membership-based relationship with Dr. Parikh.",
    icon: "crown",
    highlights: [
      "Same-day & next-day appointments",
      "Extended visit times",
      "Direct phone & text access to your physician",
      "Annual comprehensive physical",
      "Care coordination for specialists",
    ],
    image: "/services/concierge.jpg",
  },
  {
    id: "athlete-wellness",
    name: "Athlete Wellness",
    shortDesc: "Membership-based sports medicine for athletes of every age and level.",
    description:
      "Athlete Wellness is our membership-based sports medicine program built for anyone who plays, competes, trains, or simply stays active — from youth athletes to adults, weekend players to elite competitors. The focus is simple: keep you healthy, prevent injury, and get you back faster when something does go wrong. You get direct access to Dr. Parikh, same-day and next-day appointments, and a physician who understands how important your sport is to you.\n\nNeed primary care too? We can bundle it in at an upgraded membership level. Want to add in-house physical therapy or lab work? Those are available à la carte. If you're a parent looking for this level of care for your child with a full primary care relationship included, our Concierge Medicine plan is the right fit.",
    icon: "zap",
    highlights: [
      "Same-day & next-day appointments for injuries and illness",
      "Direct cell phone access to Dr. Parikh",
      "Injury prevention assessments & personalized guidance",
      "Recovery planning & return-to-sport clearance",
      "For all ages — youth through adult athletes",
      "All sports and activity levels welcome",
      "Primary care add-on available at upgraded tier",
      "Physical therapy & labs available à la carte",
    ],
    image: "/services/athlete-wellness.jpg",
  },
];

export const TESTIMONIALS = [
  {
    quote:
      "Dr. Parikh takes the time to actually listen. I never feel rushed, and he always explains everything clearly. The best primary care I've ever had.",
    author: "Sarah M.",
    detail: "Patient since 2019",
    rating: 5,
  },
  {
    quote:
      "After my knee surgery, Miral got me back to running in 10 weeks. The Fit3D scanner helped us track every bit of progress — I was blown away.",
    author: "James T.",
    detail: "Physical Therapy Patient",
    rating: 5,
  },
  {
    quote:
      "Kinnari is incredibly thorough and genuinely caring. She caught something two other doctors missed. I trust this team completely.",
    author: "Priya K.",
    detail: "Patient since 2021",
    rating: 5,
  },
  {
    quote:
      "The concierge program is worth every penny. Same-day appointments, Dr. Parikh's personal number — I feel like I actually have a real doctor again.",
    author: "David L.",
    detail: "Concierge Member",
    rating: 5,
  },
  {
    quote:
      "I came in with a sports injury that had been bothering me for months. Between Dr. Parikh's OMT and Miral's PT, I was back on the field in six weeks.",
    author: "Marcus W.",
    detail: "Sports Medicine Patient",
    rating: 5,
  },
];

export const CONDITIONS = [
  {
    id: "knee-pain",
    name: "Knee Pain",
    shortDesc: "Expert diagnosis and treatment for knee pain from injury, overuse, or arthritis.",
    description: "Knee pain is one of the most common complaints we see at ParikhHealth — from athletes with acute injuries to adults with chronic degeneration. Dr. Parikh evaluates the full picture: mechanism of injury, imaging review, functional assessment, and goals. Treatment may include osteopathic manipulation, corticosteroid or PRP injections, and a coordinated physical therapy program with our in-house PT team.",
    keywords: ["knee pain Sunnyvale", "knee injury treatment", "knee doctor Sunnyvale CA"],
    treatments: ["Physical examination & imaging review", "Corticosteroid injections", "PRP therapy", "Physical therapy & rehabilitation", "Return-to-sport planning"],
    providers: ["neesheet-parikh", "miral-patel"],
    serviceLink: "sports-medicine",
  },
  {
    id: "acl-injury",
    name: "ACL Injury & Recovery",
    shortDesc: "Comprehensive ACL evaluation, post-surgical rehabilitation, and return-to-sport clearance.",
    description: "An ACL injury can be devastating for athletes — but with the right team, recovery is achievable. ParikhHealth offers complete ACL care: initial evaluation and imaging coordination, surgical clearance, and a structured rehabilitation program through our physical therapy team. We work closely with orthopedic surgeons to ensure seamless post-op care.",
    keywords: ["ACL injury Sunnyvale", "ACL recovery physical therapy", "ACL rehab Silicon Valley"],
    treatments: ["ACL evaluation & imaging", "Post-surgical rehabilitation", "Neuromuscular training", "Return-to-sport testing & clearance", "Injury prevention programs"],
    providers: ["neesheet-parikh", "miral-patel", "sonia-sharma"],
    serviceLink: "physical-therapy",
  },
  {
    id: "back-pain",
    name: "Back Pain",
    shortDesc: "From muscle strain to disc issues — evidence-based back pain treatment including OMT.",
    description: "Back pain affects most adults at some point, and the right treatment depends entirely on the cause. Dr. Parikh's osteopathic training makes him uniquely qualified to assess and treat back pain — combining traditional primary care diagnostics with hands-on osteopathic manipulative therapy (OMT). Our physical therapists provide targeted spinal rehabilitation for chronic or post-surgical cases.",
    keywords: ["back pain doctor Sunnyvale", "lower back pain treatment", "osteopathic back pain Sunnyvale"],
    treatments: ["Osteopathic Manipulative Therapy (OMT)", "Diagnostic imaging coordination", "Anti-inflammatory injections", "Physical therapy & core stabilization", "Ergonomic & lifestyle counseling"],
    providers: ["neesheet-parikh", "harshit-bhatwala"],
    serviceLink: "primary-care",
  },
  {
    id: "sports-physical",
    name: "Sports Physical (Pre-Participation Exam)",
    shortDesc: "Clearance physicals for youth and adult athletes — fast, thorough, and sport-specific.",
    description: "A pre-participation sports physical (PPE) is required for most school-sponsored sports and recommended for any athlete beginning a new training program. At ParikhHealth, Dr. Parikh performs thorough PPEs that go beyond the basics — assessing cardiovascular health, musculoskeletal function, and sport-specific risks. Same-week appointments are usually available.",
    keywords: ["sports physical Sunnyvale", "pre-participation physical Sunnyvale CA", "sports clearance exam Bay Area"],
    treatments: ["Cardiovascular screening", "Musculoskeletal assessment", "Vision & hearing check", "Medical history review", "Same-day sport clearance when appropriate"],
    providers: ["neesheet-parikh"],
    serviceLink: "sports-medicine",
  },
  {
    id: "concussion",
    name: "Concussion Management",
    shortDesc: "Concussion evaluation, return-to-learn, and return-to-play protocols for athletes of all ages.",
    description: "Concussions require careful evaluation and structured recovery — not just rest. Dr. Parikh manages concussions using current evidence-based protocols including ImPACT testing, symptom tracking, and graduated return-to-activity programs. We coordinate with schools for return-to-learn protocols and provide return-to-sport clearance when the athlete is ready.",
    keywords: ["concussion specialist Sunnyvale", "concussion management Bay Area", "return to play concussion"],
    treatments: ["Concussion evaluation & baseline testing", "Symptom monitoring", "Return-to-learn coordination", "Graduated return-to-play protocol", "Return-to-sport clearance"],
    providers: ["neesheet-parikh"],
    serviceLink: "sports-medicine",
  },
  {
    id: "high-blood-pressure",
    name: "High Blood Pressure (Hypertension)",
    shortDesc: "Long-term hypertension management with lifestyle coaching and medication when needed.",
    description: "Hypertension is often called the 'silent killer' because it rarely causes symptoms until it causes damage. At ParikhHealth, Dr. Parikh and Kinnari Shah provide ongoing management for patients with high blood pressure — including lifestyle modifications, medication management when appropriate, and regular monitoring. The goal is to understand and address the root causes, not just treat numbers.",
    keywords: ["high blood pressure doctor Sunnyvale", "hypertension management primary care", "blood pressure treatment Sunnyvale CA"],
    treatments: ["Comprehensive blood pressure evaluation", "Lifestyle & dietary counseling", "Medication management", "Home monitoring guidance", "Regular follow-up care"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "primary-care",
  },
  {
    id: "diabetes-management",
    name: "Diabetes Management",
    shortDesc: "Personalized Type 1 and Type 2 diabetes care — monitoring, medication, and lifestyle.",
    description: "Managing diabetes well means more than keeping your A1C in check. Our team helps patients build sustainable habits, understand their numbers, and prevent complications. We manage both Type 1 and Type 2 diabetes, coordinate with endocrinologists when needed, and use the latest monitoring technologies to keep patients engaged in their own care.",
    keywords: ["diabetes doctor Sunnyvale", "diabetes management primary care Sunnyvale", "Type 2 diabetes treatment Bay Area"],
    treatments: ["A1C & glucose monitoring", "Medication & insulin management", "Nutrition & lifestyle counseling", "Diabetes education", "Specialist coordination"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "primary-care",
  },
  {
    id: "annual-physical",
    name: "Annual Physical Exam",
    shortDesc: "Comprehensive annual wellness exams for adults — preventive screenings, labs, and health planning.",
    description: "Your annual physical is the foundation of preventive health. At ParikhHealth, we don't rush through wellness visits. Dr. Parikh and Kinnari Shah take time to review your full history, order appropriate age-based screenings, discuss your health goals, and ensure your preventive care is up to date. We accept most PPO insurance plans and offer self-pay rates.",
    keywords: ["annual physical Sunnyvale", "wellness exam Sunnyvale CA", "physical exam doctor Sunnyvale"],
    treatments: ["Complete physical examination", "Preventive screenings (age & risk-based)", "Laboratory work", "Immunizations & vaccines", "Health goal setting"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "primary-care",
  },
  {
    id: "rotator-cuff",
    name: "Rotator Cuff Injury",
    shortDesc: "Rotator cuff evaluation, injection therapy, and guided rehabilitation for shoulder pain.",
    description: "Rotator cuff injuries range from mild tendinitis to full thickness tears — and each requires a different approach. Dr. Parikh evaluates shoulder injuries with a thorough exam and imaging when needed, and our physical therapy team provides expert rehabilitation. For many patients, surgery can be avoided with a structured non-operative treatment plan.",
    keywords: ["rotator cuff injury Sunnyvale", "shoulder pain doctor Sunnyvale", "shoulder PT Silicon Valley"],
    treatments: ["Shoulder examination & imaging", "Corticosteroid or PRP injections", "Physical therapy & rotator cuff strengthening", "Post-surgical rehabilitation", "Return-to-sport planning"],
    providers: ["neesheet-parikh", "miral-patel"],
    serviceLink: "sports-medicine",
  },
  {
    id: "plantar-fasciitis",
    name: "Plantar Fasciitis",
    shortDesc: "Treatment for heel pain and plantar fasciitis — from runners to everyday patients.",
    description: "Plantar fasciitis is one of the most common causes of heel pain and can be frustrating to treat without the right approach. At ParikhHealth, we combine Dr. Parikh's sports medicine expertise with our physical therapy team's hands-on rehabilitation to address the root biomechanical causes — not just the symptoms.",
    keywords: ["plantar fasciitis treatment Sunnyvale", "heel pain doctor Sunnyvale CA", "foot pain sports medicine Bay Area"],
    treatments: ["Biomechanical assessment", "Stretching & strengthening protocols", "Orthotics counseling", "Corticosteroid injections when appropriate", "Shockwave therapy referral if needed"],
    providers: ["neesheet-parikh", "harshit-bhatwala"],
    serviceLink: "sports-medicine",
  },
  {
    id: "womens-wellness-exam",
    name: "Women's Wellness Exam",
    shortDesc: "Annual well-woman exams, Pap smears, and comprehensive women's preventive care.",
    description: "ParikhHealth provides compassionate, thorough women's wellness care in a comfortable and private environment. Our annual well-woman exams include cervical cancer screening, breast exams, STI screening, contraception counseling, and menopause or perimenopause support. We believe women deserve a provider who listens carefully and takes their concerns seriously.",
    keywords: ["women's wellness exam Sunnyvale", "Pap smear Sunnyvale CA", "gynecology primary care Sunnyvale"],
    treatments: ["Annual well-woman exam", "Pap smear & cervical cancer screening", "Clinical breast exam", "Contraception counseling", "Menopause & hormone discussions"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "womens-health",
  },
  {
    id: "botox-sunnyvale",
    name: "Botox & Neurotoxin Treatments",
    shortDesc: "Physician-administered Botox and neurotoxin treatments for natural-looking results.",
    description: "At ParikhHealth, cosmetic treatments are performed under direct physician oversight — not delegated to non-medical staff. Dr. Parikh administers Botox and neurotoxin treatments with a precise, conservative approach focused on natural-looking results. Medical oversight means faster response if any complication arises and a higher standard of safety.",
    keywords: ["Botox Sunnyvale", "Botox physician Sunnyvale CA", "neurotoxin treatment Bay Area"],
    treatments: ["Botox (forehead, frown lines, crow's feet)", "Dysport & Xeomin", "Preventive Botox", "Hyperhidrosis (excessive sweating) treatment", "Medical-grade skincare consultation"],
    providers: ["neesheet-parikh"],
    serviceLink: "cosmetics",
  },
  {
    id: "annual-wellness-exam",
    name: "Annual Wellness Exam",
    shortDesc: "Comprehensive annual wellness exams for adults in Sunnyvale — preventive care, labs, and health planning.",
    description: "Your annual wellness exam is your most important appointment of the year. At ParikhHealth in Sunnyvale, CA, Dr. Parikh and Kinnari Shah, PA-C conduct thorough preventive visits tailored to your age, sex, and personal health history. We go beyond checking boxes — we spend real time understanding your goals, ordering appropriate screenings, reviewing your medications, and building a preventive care plan that actually fits your life. Most PPO insurance plans cover annual wellness exams at no cost to you.",
    keywords: ["annual wellness exam Sunnyvale", "wellness exam doctor Sunnyvale CA", "preventive care Sunnyvale", "annual checkup Sunnyvale CA", "yearly physical Sunnyvale"],
    treatments: ["Complete head-to-toe physical examination", "Age-appropriate preventive screenings", "Comprehensive laboratory bloodwork", "Immunizations & vaccine review", "Chronic disease monitoring", "Health goal setting & lifestyle planning"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "primary-care",
  },
  {
    id: "breast-exam",
    name: "Clinical Breast Exam",
    shortDesc: "Clinical breast exams and breast health guidance as part of your annual women's wellness visit.",
    description: "Early detection is the most powerful tool in breast cancer outcomes. At ParikhHealth, clinical breast exams are a standard part of every women's wellness visit. Dr. Parikh and Kinnari Shah, PA-C conduct thorough breast examinations, review your personal and family history for risk factors, and coordinate mammography referrals based on current USPSTF and ACR screening guidelines. We also counsel patients on breast self-awareness and what changes to watch for between visits.",
    keywords: ["clinical breast exam Sunnyvale", "breast exam doctor Sunnyvale CA", "breast health primary care Sunnyvale", "breast cancer screening Sunnyvale", "mammogram referral Sunnyvale"],
    treatments: ["Clinical breast examination", "Breast cancer risk assessment", "Mammography coordination & referrals", "Breast self-examination guidance", "Genetic risk counseling referral if indicated"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "womens-health",
  },
  {
    id: "pap-smear",
    name: "Pap Smear & Cervical Cancer Screening",
    shortDesc: "Pap smears and HPV co-testing for cervical cancer prevention — covered by most PPO plans.",
    description: "Cervical cancer is one of the most preventable cancers when Pap smears and HPV testing are performed on schedule. At ParikhHealth in Sunnyvale, we follow current USPSTF and ACOG screening guidelines — Pap smears every 3 years for women aged 21–65, or every 5 years with HPV co-testing. Results are reviewed promptly and we coordinate any needed colposcopy or specialist referrals. Our office provides a private, comfortable environment for these sensitive exams.",
    keywords: ["Pap smear Sunnyvale", "cervical cancer screening Sunnyvale CA", "HPV test Sunnyvale", "Pap smear doctor Sunnyvale", "gynecology primary care Sunnyvale CA"],
    treatments: ["Pap smear (cervical cytology)", "HPV co-testing", "Abnormal Pap follow-up", "Colposcopy referral coordination", "HPV vaccination counseling"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "womens-health",
  },
  {
    id: "womens-health",
    name: "Women's Health Primary Care",
    shortDesc: "Comprehensive women's health care in Sunnyvale — from preventive screenings to hormone health.",
    description: "Women's health encompasses far more than reproductive care. At ParikhHealth, we provide comprehensive primary care tailored specifically to women's health needs across every life stage — from annual wellness exams and contraception counseling in your 20s, to perimenopause support and bone health in your 40s and 50s, to preventive screenings and chronic disease management as you age. Dr. Parikh and Kinnari Shah, PA-C are experienced in treating the whole woman, not just a list of symptoms.",
    keywords: ["women's health doctor Sunnyvale", "women's primary care Sunnyvale CA", "women's healthcare Sunnyvale", "women's preventive care Sunnyvale", "OBGYN primary care Sunnyvale CA"],
    treatments: ["Annual well-woman exams", "Contraception counseling & management", "Menopause & perimenopause care", "Hormone health discussions", "Osteoporosis screening & prevention", "Preventive cancer screenings"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "womens-health",
  },
  {
    id: "sexual-health",
    name: "Sexual Health & STI Screening",
    shortDesc: "Confidential STI testing, sexual health counseling, and PrEP in Sunnyvale, CA.",
    description: "Sexual health is an important part of overall health, and ParikhHealth provides confidential, non-judgmental sexual health care for all patients. We offer comprehensive STI screening including HIV, gonorrhea, chlamydia, syphilis, hepatitis B and C, and HPV. We provide PrEP (pre-exposure prophylaxis) for HIV prevention, contraception counseling, and LGBTQ+-affirming care. All visits are completely confidential within the limits of applicable law.",
    keywords: ["STI testing Sunnyvale", "sexual health doctor Sunnyvale CA", "STD screening Sunnyvale", "PrEP Sunnyvale CA", "confidential STI testing Sunnyvale"],
    treatments: ["Comprehensive STI panel testing", "HIV testing & PrEP counseling", "Contraception counseling", "HPV vaccination", "LGBTQ+-affirming primary care", "Partner notification guidance"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "womens-health",
  },
  {
    id: "well-woman-exam",
    name: "Well-Woman Exam",
    shortDesc: "Well-woman visits in Sunnyvale — Pap smears, breast exams, contraception, and whole-person care.",
    description: "A well-woman exam is more than a Pap smear — it's your dedicated annual time with a provider who knows your full health picture. At ParikhHealth in Sunnyvale, our well-woman visits include a complete physical, clinical breast exam, cervical cancer screening (when due), discussion of contraception or menopause management, STI risk assessment, mental health check-in, and any laboratory work indicated by your age and history. We accept most PPO plans and offer transparent self-pay rates.",
    keywords: ["well-woman exam Sunnyvale", "well woman visit Sunnyvale CA", "annual women's exam Sunnyvale", "OB-GYN primary care Sunnyvale", "women's annual exam Sunnyvale CA"],
    treatments: ["Complete physical examination", "Pap smear & HPV testing (when due)", "Clinical breast examination", "Contraception counseling", "Menopause management", "Preventive labs & immunizations"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "womens-health",
  },
  {
    id: "primary-care",
    name: "Primary Care in Sunnyvale, CA",
    shortDesc: "Board-certified primary care for the whole family in Sunnyvale — same-week appointments available.",
    description: "ParikhHealth is a direct-access primary care practice in Sunnyvale, CA serving adults and adolescents with comprehensive, relationship-based medical care. Dr. Neesheet Parikh, DO and Kinnari Shah, PA-C provide chronic disease management, acute illness care, preventive screenings, and coordination of specialty care — all under one roof. Unlike large health systems, we offer same-week appointments, direct physician access, and visits that never feel rushed. Conveniently located at 1299 Oakmead Parkway in Sunnyvale with easy freeway access.",
    keywords: ["primary care Sunnyvale CA", "primary care doctor Sunnyvale", "family doctor Sunnyvale CA", "internal medicine Sunnyvale", "PCP Sunnyvale CA", "best primary care Sunnyvale"],
    treatments: ["Preventive care & annual exams", "Chronic disease management", "Acute illness & injury care", "Medication management", "Specialty referral coordination", "In-office labs & diagnostics"],
    providers: ["neesheet-parikh", "kinnari-shah"],
    serviceLink: "primary-care",
  },
  {
    id: "botox",
    name: "Botox Injections in Sunnyvale",
    shortDesc: "Physician-administered Botox in Sunnyvale, CA — natural results with medical-grade safety.",
    description: "Botox at ParikhHealth is performed exclusively by Dr. Neesheet Parikh, DO — not by nurses or aestheticians. Physician-administered injections mean a deeper understanding of facial anatomy, more precise placement, and immediate medical management if any reaction occurs. Dr. Parikh takes a conservative, natural-looking approach: the goal is to look refreshed, not frozen. Common treatment areas include forehead lines, glabellar frown lines, crow's feet, brow lift, and hyperhidrosis (excessive sweating). Serving Sunnyvale, Santa Clara, San Jose, and the greater Silicon Valley area.",
    keywords: ["Botox Sunnyvale CA", "Botox injections Sunnyvale", "Botox doctor Sunnyvale", "physician Botox Sunnyvale CA", "Botox near me Sunnyvale", "cosmetic Botox Silicon Valley"],
    treatments: ["Forehead line treatment", "Frown lines (glabellar lines)", "Crow's feet treatment", "Brow lift", "Bunny lines", "Hyperhidrosis (excessive sweating) Botox"],
    providers: ["neesheet-parikh"],
    serviceLink: "cosmetics",
  },
  {
    id: "microneedling",
    name: "Microneedling in Sunnyvale",
    shortDesc: "Medical-grade microneedling for skin texture, acne scars, and anti-aging — physician-supervised.",
    description: "Microneedling uses controlled micro-injuries to stimulate your skin's natural collagen and elastin production — improving texture, reducing acne scars, minimizing pores, and smoothing fine lines. At ParikhHealth, microneedling is performed with medical-grade devices under physician supervision, which allows for deeper treatment depths and better results than spa-grade options. A series of 3–6 sessions is typically recommended, with noticeable improvement beginning after the first treatment. PRP (platelet-rich plasma) can be added to enhance results.",
    keywords: ["microneedling Sunnyvale CA", "microneedling doctor Sunnyvale", "collagen induction therapy Sunnyvale", "acne scar treatment Sunnyvale CA", "microneedling with PRP Sunnyvale"],
    treatments: ["Medical-grade microneedling", "Microneedling with PRP (vampire facial)", "Acne scar reduction", "Fine line & wrinkle improvement", "Pore minimization", "Skin texture & tone enhancement"],
    providers: ["neesheet-parikh"],
    serviceLink: "cosmetics",
  },
  {
    id: "prp-hair-restoration",
    name: "PRP Hair Restoration in Sunnyvale",
    shortDesc: "PRP injections for hair loss and thinning — physician-administered, non-surgical hair restoration.",
    description: "Platelet-rich plasma (PRP) therapy for hair restoration uses your body's own growth factors to stimulate dormant hair follicles and slow hair loss. At ParikhHealth, Dr. Parikh performs PRP hair restoration using a precise, evidence-informed protocol — drawing a small blood sample, concentrating the platelets, and injecting the activated PRP directly into thinning areas of the scalp. Best results are seen in patients with androgenetic alopecia (pattern hair loss) who still have some active follicles. A typical course involves 3 monthly sessions followed by quarterly maintenance.",
    keywords: ["PRP hair restoration Sunnyvale CA", "PRP hair loss treatment Sunnyvale", "hair loss doctor Sunnyvale CA", "platelet rich plasma hair Sunnyvale", "non-surgical hair restoration Silicon Valley"],
    treatments: ["PRP scalp injections", "Blood draw & PRP preparation", "Hair loss assessment", "Androgenetic alopecia treatment", "Quarterly maintenance sessions", "Combined therapy planning (PRP + topical/oral)"],
    providers: ["neesheet-parikh"],
    serviceLink: "cosmetics",
  },
  {
    id: "prp-facial",
    name: "PRP Facial (Vampire Facial) in Sunnyvale",
    shortDesc: "PRP facial treatments in Sunnyvale — physician-performed for skin rejuvenation and collagen stimulation.",
    description: "The PRP facial — sometimes called the vampire facial — combines microneedling with platelet-rich plasma to deliver concentrated growth factors deep into the skin. At ParikhHealth, Dr. Parikh performs PRP facials under physician supervision, ensuring proper preparation, sterile technique, and treatment depth that medical-grade devices allow. Results include improved skin tone, reduced fine lines, smaller pores, and a natural glow — without fillers or downtime. Patients typically see optimal results after a series of 3 treatments spaced 4–6 weeks apart.",
    keywords: ["PRP facial Sunnyvale CA", "vampire facial Sunnyvale", "PRP microneedling Sunnyvale CA", "PRP skin treatment Sunnyvale", "platelet rich plasma facial Silicon Valley"],
    treatments: ["PRP preparation & activation", "Microneedling with PRP application", "Topical PRP treatment", "Skin rejuvenation consultation", "Post-treatment skincare guidance", "Series treatment planning"],
    providers: ["neesheet-parikh"],
    serviceLink: "cosmetics",
  },
];
